pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    sh 'ls -l target/surefire-reports/'  // List files to verify
                    junit '**/target/surefire-reports/*.xml'  // Publish JUnit reports
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './deliver.sh'
            }
        }
    }
}
